// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package base

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Show() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><style type=\"text/css\">\n        main {\n            display: flex;\n            flex-direction: column;\n            align-items: center;\n        }\n\n        #title {\n            font-size: 16px;\n            color: red;\n        }\n\n        #frames {\n            margin-left: 50px;\n            margin-right: 50px;\n            width: 100%;\n            height: 22rem;\n\n            border: 5px solid white;\n            display: flex;\n            flex-direction: row;\n        }\n\n        #ascii {\n            margin: 0;\n            padding: 0;\n            font-family: 'Courier';\n            font-size: 8px;\n            line-height: 5pt;\n        }\n\n        .display {\n            width: 50%;\n            border-left: 2px ridge gray;\n        }\n    </style><main><h1 id=\"title\">ASCII Filter</h1><div id=\"frames\"><video id=\"video\" class=\"display\" autoplay></video><div id=\"blob\" class=\"display\"><p id=\"ascii\"></p></div><canvas id=\"frameCanvas\" style=\"display:none;\"></canvas></div><button id=\"start\">Start Recording</button></main><script src=\"/static/js/index.js\" defer></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
